spring.application.name=stadium-booking

spring.datasource.url=jdbc:postgresql://localhost:5432/stadium_booking_db
spring.datasource.username=postgres
spring.datasource.password=123POSTsql@@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${JWT_SECRET}
app.jwt.access-token-minutes=30
app.jwt.refresh-token-days=14